name: test

on:
  push:
    branches:
      - '*'
      - '*/*'
  pull_request:
    types: [opened, reopened, synchronize]

env:
  TS_NODE_TRANSPILE_ONLY: 1
  FORCE_COLORS: 1

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly


      - run: yarn install


      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
